language: java
jdk:
  - openjdk8
notifications:
  email: ryanucheka@gmail.com

services:
  - docker

before_install:
  - docker pull openjdk:8-jdk-alpine
script:
  - mvn clean compile jib:build

#after_success:
#  - export COMMIT=${TRAVIS_COMMIT::7}
##  - export TAG=`if [ ! -z "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG"; else echo "$TRAVIS_BRANCH--$COMMIT"; fi`
#  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#  - docker build -t $IMAGE_NAME:$COMMIT .
##  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
#  - docker push $IMAGE_NAME

#deploy:
#  provider: heroku
#  api_key: $HEROKU_API_KEY
#  on:
#    tags: true
#    repo: $IMAGE_NAME
#
#after_deploy:
#  - export TITLE="🎉🎉🎉New version $TAG is deployed to Heroku production🎉🎉🎉"
#  - export TEXT=[datetime]:`date`