language: java
jdk:
  - openjdk8
notifications:
  email: ryanucheka@gmail.com

services:
  - docker

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker login -u $HEROKU_USERNAME --password=$HEROKU_TOKEN registry.heroku.com

#install:
#  # INSTALL DEPENDENCIES
#  - docker pull openjdk:8-jdk-alpine

script:
#  - mvn clean package -DskipTests
  # build docker images
  - docker build -t ucheka22/zatech-app .
  - docker tag ucheka22/zatech-app registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
  provider: script
  script:
    # push to dockerhub & heroku
    docker push ucheka22/zatech-app;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME
  on:
    branch: develop
#script:
#  - mvn clean compile jib:build

#after_success:
#  - export COMMIT=${TRAVIS_COMMIT::7}
##  - export TAG=`if [ ! -z "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG"; else echo "$TRAVIS_BRANCH--$COMMIT"; fi`
#  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#  - docker build -t $IMAGE_NAME:$COMMIT .
##  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
#  - docker push $IMAGE_NAME
#deploy:
#  provider: heroku
#  api_key: $HEROKU_API_KEY
#  on:
#    branch: develop
#
#after_deploy:
#  - export TITLE="🎉🎉🎉New version $TAG is deployed to Heroku production🎉🎉🎉"
#  - export TEXT=[datetime]:`date`